import { useState, useEffect, useRef } from 'react';

const CppDemo = () => {
    const [inputNum, setInputNum] = useState(10); // Defaults to 10
    const [result, setResult] = useState(null);
    const [wasmModule, setWasmModule] = useState(null);
    const [timeTaken, setTimeTaken] = useState(null);

    useEffect(() => {
        // Load in external JS file generated by Emscripten
        const script = document.createElement('script');
        script.src = "/wasm_demo.js";
        script.async = true;

        script.onload = () => {
            if (window.createModule) {
            window.createModule().then((module) => {
                setWasmModule(module);
                console.log("C++ Module Loaded!");
            });
        } else {
            console.error("Wasm module failed to load. Check public/wasm_demo.js");
        }
        };

        document.body.appendChild(script);

        return () => {
            document.body.removeChild(script);
        }
    }, []);

    const handleInputChange = (e) => {
        let val = parseInt(e.target.value);

        if (isNaN(val)) {
            setInputNum("");
            return;
        }

        //Hard Limit: Max 40 to prevent browser freezing
        if (val > 40) val =40;
        // Hard Limit: Min 0
        if (val < 0) val = 0;

        setInputNum(val);

    };

    const calculate = () => {
        if (!wasmModule) return;

        const start = performance.now();
        const res = wasmModule.fibonacci(inputNum);
        const end = performance.now();

        setResult(res);
        setTimeTaken((end - start).toFixed(4));
    };

    return (
        <div className="bg-slate-800 text-white p-6 rounded-lg shadow-xl mt-8 w-full overflow-hidden">
            <h2 className="text-2-xl font-bold mb-4 border-b border-gray-600 pb-2">
                ⚡ C++ WebAssembly Power
            </h2>
            <p className="text-gray-300 text-sm mb-4">
                Native C++ Fibonacci calculator running in-browser.
            </p>

            <div className="flex gap-4 items-center mb-4">
                <div className="flex flex-col">
                    <label className="text-xs text-gray-400 mb-1">Index (Max 40)</label>
                    <input
                        type="number"
                        value={inputNum}
                        onChange={handleInputChange}
                        placeholder="1-40"
                        className="text-black p-2 rounded w-24 outline-none focus:ring-2 focus:ring-green-500"
                        min="0"
                        max="40" // Setting this too high will break the browser
                    />
                </div>
                <button
                onClick={calculate}
                disabled={!wasmModule || inputNum === ""}
                className="mt-5 bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded font-bold 
                transition disabled:opacity-50 disabled:cursor-not-allowed"
                >
                    Run C++
                </button>
                </div>

                {result !== null && (
                    <div className="bg-slate-900 p-4 rounded border border-gray-700 animate-pulse-once">
                        <p className="text-gray-400 text-sm">Fibonacci({inputNum}) =</p>
                        <p>Result: <span className="text-green-400 font-mono text-xl">{result}</span></p>

                        <p className="text-xs text-gray-400 mt-1">Time: {timeTaken}ms</p>
                    </div>
                )}
            </div>
    );
}

export default CppDemo;
