import { useState, useEffect, useRef } from 'react';

const CppDemo = () => {
    const [inputNum, setInputNum] = useState(10);
    const [result, setResult] = useState(null);
    const [wasmModule, setWasmModule] = useState(null);
    const [timeTaken, setTimeTaken] = useState(null);

    useEffect(() => {
        // Load in external JS file generated by Emscripten
        const script = document.createElement('script');
        script.src = "/wasm_demo.js";
        script.async = true;

        script.onload = () => {
            if (window.createModule) {
            window.createModule().then((module) => {
                setWasmModule(module);
                console.log("C++ Module Loaded!");
            });
        } else {
            console.error("Wasm module failed to load. Check public/wasm_demo.js");
        }
        };

        document.body.appendChild(script);

        return () => {
            document.body.removeChild(script);
        }
    }, []);

    const calculate = () => {
        if (!wasmModule) return;

        const start = performance.now();
        const res = wasmModule.fibonacci(inputNum);
        const end = performance.now();

        setResult(res);
        setTimeTaken((end - start).toFixed(4));
    };

    return (
        <div className="bg-slate-800 text-white p-6 rounded-lg shadow-xl mt-8 max-w-md">
            <h2 className="text-2-xl font-bold mb-4 border-b border-gray-600 pb-2">
                ⚡ C++ WebAssembly Power
            </h2>
            <p className="text-gray-300 text-sm mb-4">
                This calculation runs natively in C++ inside your browser using WebAssembly.
            </p>

            <div className="flex gap-4 items-center mb-4">
                <label className="text-sm">Fibonacci Index:</label>
                <input
                    type="number"
                    value={inputNum}
                    onChange={(e) => 
                        setInputNum(parseInt(e.target.value))}
                        className="text-black p-2 rounded w-20"
                        min="1"
                        max="40" // Setting this too high will break the browser
                    />
                    <button
                    onClick={calculate}
                    disabled={!wasmModule}
                    className="bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded font-bold 
                    transition disabled:opacity-50"
                    >
                        Run C++
                    </button>
                    </div>

                    {result !== null && (
                        <div className="bg-slate-900 p-4 rounded border border-gray-700">
                            <p>Result: <span className="text-green-400 font-mono text-xl">{result}</span></p>

                            <p className="text-xs text-gray-400 mt-1">Computation Time: {timeTaken}ms</p>
                        </div>
                    )}
            </div>
    );
}

export default CppDemo;
